### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nathanclevenger** [drivly/Roadmap#1]
```[tasklist]
## 🚘 Commerce
- [ ] Add a draft title or issue reference here
```

```[tasklist]
## 🛠️ Services
- [ ] Add a draft title or issue reference here
```

```[tasklist]
## 📖 Data
- [ ] Add a draft title or issue reference here
```
